on:
  push:
    branches-ignore:
      - 'main'
  pull_request: 
    branches-ignore:
      - 'main'
jobs:
  setup-dotnet:
    runs-on: 
      windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
          
      - name: Install Dependencies
        run: dotnet restore
  
  run-beginner-tests:
    runs-on: windows-latest
    needs: setup-dotnet
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run Beginner Tests
        run: dotnet test .\Tests\BeginnerTests\